package com.wipay.payment.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable (tableName = "tbl_audit_payment")
public class AuditPayment {
    
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    
    @DynamoDBAttribute (attributeName = "idTransaction")
    private String idTransaction;
    private String reconciliationId;
    
    private String clientReferenceInformationCode;
    
    private String dateTransaction;
    
    public String getId() {
        return id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    public String getIdTransaction() {
        return idTransaction;
    }
    
    public void setIdTransaction(String idTransaction) {
        this.idTransaction = idTransaction;
    }
    
    public String getReconciliationId() {
        return reconciliationId;
    }
    
    public void setReconciliationId(String reconciliationId) {
        this.reconciliationId = reconciliationId;
    }
    
    public String getClientReferenceInformationCode() {
        return clientReferenceInformationCode;
    }
    
    public void setClientReferenceInformationCode(String clientReferenceInformationCode) {
        this.clientReferenceInformationCode = clientReferenceInformationCode;
    }
    
    public String getDateTransaction() {
        return dateTransaction;
    }
    
    public void setDateTransaction(String dateTransaction) {
        this.dateTransaction = dateTransaction;
    }
}
