package com.wipay.payment.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable (tableName = "tbl_audit_payment")
public class AuditPayment {
    
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    public AuditPayment(String id, String idTransaction, String reconciliationId, String clientReferenceInformationCode) {
    }

    public String getPK() {
        return PK;
    }

    public void setPK(String PK) {
        this.PK = PK;
    }

    private String PK;


    public AuditPayment(String id){
        this.PK = String.format("%s#%s", KeyPrefixes.AuditPayment.getValue(), id);
    }
    
    @DynamoDBAttribute (attributeName = "idTransaction")
    private String idTransaction;
    private String reconciliationId;
    
    private String clientReferenceInformationCode;
    
    private String dateTransaction;

    public AuditPayment() {
        this.id = id;
        this.idTransaction = idTransaction;
        this.reconciliationId = reconciliationId;
        this.clientReferenceInformationCode = clientReferenceInformationCode;
        this.dateTransaction = dateTransaction;
    }

    public String getId() {
        return id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    public String getIdTransaction() {
        return idTransaction;
    }
    
    public void setIdTransaction(String idTransaction) {
        this.idTransaction = idTransaction;
    }
    
    public String getReconciliationId() {
        return reconciliationId;
    }
    
    public void setReconciliationId(String reconciliationId) {
        this.reconciliationId = reconciliationId;
    }
    
    public String getClientReferenceInformationCode() {
        return clientReferenceInformationCode;
    }
    
    public void setClientReferenceInformationCode(String clientReferenceInformationCode) {
        this.clientReferenceInformationCode = clientReferenceInformationCode;
    }
    
    public String getDateTransaction() {
        return dateTransaction;
    }
    
    public void setDateTransaction(String dateTransaction) {
        this.dateTransaction = dateTransaction;
    }

    @DynamoDBIgnore
    public AuditPayment getAuditPayment(){
        return new AuditPayment(
                this.id
        );
    }
}
